[build]
  command = "npm run build"
  publish = "dist"

# Single Page App fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure SW updates promptly
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# (Optional) correct manifest MIME
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
