[build]
  command = "npm run build"
  publish = "dist"

# Single Page App routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PWA: serve manifest with correct MIME
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

# PWA: ensure service worker updates
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
